### ISSUE TITLE
URI Access not working

### ISSUE THREAD

**Issue by mrmmg** [aamplugin/advanced-access-manager#112]
Hi
I set URI access for a role (in my case: author) that can change their password. But URI accesses not working. My URI is: `/wp-admin/profile.php` But **AAM Return Access Denied**. Can you help me?

**Comment by aamplugin** [comment]
Indeed if you restrict access to the URI, AAM will return access denied default message. What exactly are you trying to accomplish?

**Comment by mrmmg** [comment]
I make access to `/wp-admin/profile.php` but **AAM will return access denied default message**.  Why access denied when I make access to that URI? **I want that user can access to that but it not happening**.

**Comment by aamplugin** [comment]
I believe the issue you've described is related to #131
