### ISSUE TITLE
Passwordless authentication disregards "redirect_to" query param

### ISSUE THREAD

**Issue by aamplugin** [aamplugin/advanced-access-manager#117]
When login with passwordless URL, AAM does not take into consideration `redirect_to` query param and only checks for the Login Redirect settings.

Ideally, AAM should use `redirect_to` as the first tier, then fallback to Login Redirect settings. Finally, if neither are defined, apply default system login redirect.

**Comment by nicolas347322** [comment]
Great! Can I be tester?
Thanks.

**Comment by aamplugin** [comment]
> Great! Can I be tester?
> Thanks.

All set. You can checkout `master` branch and run tests. Thank you for volunteering.
