### ISSUE TITLE
Simplify `aam/v2/authenticate` output

### ISSUE THREAD

**Issue by aamplugin** [aamplugin/advanced-access-manager#139]
Changing the output for the `aam/v2/authenticate`. Previously, AAM was returning the complete WP_User object data. This should be controlled list of options to avoid exposing any unwanted information.

**Comment by aamplugin** [comment]
The new output contains the following information:

```
{
    "user": {
        "data": {
            "ID": 12,
            "user_login": "vasyl",
            "user_nicename": "vasyl",
            "display_name": "Vasyl Martyniuk",
            "user_url": "",
            "user_email": "vasyl@someemaildomain.com",
            "user_registered": "2019-12-10 01:02:54"
        }
    },
    "redirect": null,
    "jwt": {
        "token": "eyJ0eXAiOiJKV1QiLCJhaGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTc1MTE2MTUsImlzcyI6Imh0dHA6XC9cL2Rldi53b3JkcHJlc3MiLCJleHAiOjE1OTc1OTgwMTUsImp1aSI6IjliYjk1ZTU1LThlZjAtNGI2Ny1iMjc2LWY0Mzg1OTAwMzI4OCIsInVzZXJJZCI6MSwicmV2b2NhYmxlIjp0cnVlLCJyZqZyZXzoYWJsZSI6bnVsbH0.ZeimqSE8Lx4o2KR-KSXgY0x13iPP3pZzYJbXj0y7jUQ",
        "token_expires": 1597598015
    }
}
```

**Comment by luisjoserivera** [comment]
Thanks for letting us know.
It would be good to point out the new output is now an array. Previously it was an object.

**Comment by luisjoserivera** [comment]
Hey @aamplugin 
Why don't just append the actual user data right under the "user" property. It will be much cleaner and simpler to work with.
```
{
    "user": {
        "ID": 12,
        "user_login": "vasyl",
        "user_nicename": "vasyl",
        "display_name": "Vasyl Martyniuk",
        "user_url": "",
        "user_email": "vasyl@someemaildomain.com",
        "user_registered": "2019-12-10 01:02:54"
    },
    "redirect": null,
    "jwt": {
        "token": "eyJ0eXAiOiJKV1QiLCJhaGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTc1MTE2MTUsImlzcyI6Imh0dHA6XC9cL2Rldi53b3JkcHJlc3MiLCJleHAiOjE1OTc1OTgwMTUsImp1aSI6IjliYjk1ZTU1LThlZjAtNGI2Ny1iMjc2LWY0Mzg1OTAwMzI4OCIsInVzZXJJZCI6MSwicmV2b2NhYmxlIjp0cnVlLCJyZqZyZXzoYWJsZSI6bnVsbH0.ZeimqSE8Lx4o2KR-KSXgY0x13iPP3pZzYJbXj0y7jUQ",
        "token_expires": 1597598015
    }
}
```

**Comment by aamplugin** [comment]
@luisjoserivera,

I'm with you on that one it just I have to keep backward compatibility because prior to this change, the "user" prop contains the full dump of WP_User object and I know for a fact that most of the websites that rely on this information will look for data in the `user.data` object.

Shortly, I'm going to document this functionality and release new version of endpoint that will produce output more looking you've mentioned.

**Comment by luisjoserivera** [comment]
I get it. Anyway, backward compatibility was kinda broken after all because user ID used to come right bellow the user property. like:
```php
{
    "user": {
        "ID": 12,
        "data": ... 
    }
}```
