### ISSUE TITLE
Imposible to allow manage_links

### ISSUE THREAD

**Issue by rybarova** [aamplugin/advanced-access-manager#141]
I have big problem to allow manage_links due that that option is unmarked after refresh. I treid everything. I have enabled all capatibilities but manage_links is still unmarked after refresh. It's really cancer friendly because due of this that I can't set primary category.
Can you show me the way, how to enable this option or fix that bug?

**Comment by aamplugin** [comment]
Hello @rybarova,

That is not really AAM related question as it is WordPress's core capability, however, more than happy to clarify the situation.

So, `manage_links` capability is an exceptional capability. WordPress core has over 60 exceptions defined in its code and some are not as intuitive as you might think. You can see all the exceptions implemented in the `/wp-content/capabilities.php` file.

When it comes to working with `manage_links`, you have to make sure that the WordPress core option `link_manager_enabled` is enabled. Otherwise, it'll be ignored. You can find the `link_manager_enabled` option in the `wp_options` database table and just set to `1`. If it does not exist, create it.

That will do the trick.

**Comment by rybarova** [comment]
It works, thank you for your time and clarifying situation. Thumb Down for WordPress.

I find another solution. If somebody have not access or courage to edit database, you can use this as well in functions.php or in own module.
`add_filter( 'pre_option_link_manager_enabled', '__return_true' );`

**Comment by aamplugin** [comment]
@rybarova that is one of the ways to do it. However, I would strongly encourage avoiding this approach. You are quite literally suppressing the flexible option in the code, which is not ideal.

There are two possible solutions that are a bit better:

- Change the  `link_manager_enabled` in the `wp_options` to 1;
- Define AAM Access Policy that you can attach to any user, role or everybody at once that allows managing links:

```
{
    "Param": [
        {
            "Key": "option:link_manager_enabled",
            "Value": 1
        }
    ]
}
```

<img width="1440" alt="Screen Shot 2020-08-26 at 4 25 10 PM" src="https://user-images.githubusercontent.com/34006503/91353095-c696ed00-e7b8-11ea-958c-c525b58c347b.png">

With the second option, you can control WHO can actually manage those links. Let's say in the screenshot above ONLY users with the Administrator role can manage links

**Comment by rybarova** [comment]
Thank you for remind me this feature the 'Access Policy'. This your second solution is probably best.

**Comment by aamplugin** [comment]
@rybarova keep me posted if the solution worked for you.

I also noticed your review on the official WordPress repository https://wordpress.org/support/topic/worst-support-and-many-bugs/.

You've stated that there are multiple bugs. Can you please share more information on it?

Thank you

**Comment by rybarova** [comment]
Many bugs and issues you can see at [support page](https://wordpress.org/support/plugin/advanced-access-manager/) of this plugin. And you can find as well [my post](https://wordpress.org/support/topic/unable-to-allow-manage_links/) which i posted 3 months, 2 weeks ago (still without reply).
Finally when I got rage about this and posted that review and tried GitHub also I got help.
Without GitHub and that review I am probably still Waiting for reply like others there. 
My Issue is solved, but there is more people who have some bugs and no reply. Your new support policy moves conversation from that support page to your own pages, which does not have to show all issues.
