### ISSUE TITLE
User Level Filter Service: Performance Request

### ISSUE THREAD

**Issue by dannysummerlinjstartorg** [aamplugin/advanced-access-manager#142]
https://github.com/aamplugin/advanced-access-manager/blob/fe2a009df621d60b488e442876efa992286d218e/Application/Core/API.php#L176

Great plugin, but we have found it can get slow, and one small tweak to make things faster is to skip this regex if we can, so we edited line 176 to

` if (!empty($granted) && (strpos($cap, 'level') !== false) && preg_match('/^level_([0-9]+)$/', $cap, $match)) {`

adding the `&& (strpos($cap, 'level') !== false)'` to skip level checks if they aren't in use. There may be other places, but that is one we have found helpful.

**Comment by aamplugin** [comment]
@dannysummerlinjstartorg sounds like a reasonable ask. Besides, it makes more sense to avoid using preg_match in this situation to improve performance.
