### ISSUE TITLE
AAM CLI: Allow the ability import/export settings

### ISSUE THREAD

**Issue by aamplugin** [aamplugin/advanced-access-manager#150]
Allow the ability to import/export any AAM settings. More details to come.

**Comment by eriksays** [comment]
Hi! -- I requested this feature.

The use case for this is to utilize wp cli to export settings from an existing site and use the json file to import to other sites that need the same settings. 

I have uploaded the two screens that this functionality currently resides. This is what we'd like to request be made available via CLI


<img width="613" alt="Screen Shot 2020-10-01 at 9 03 44 AM" src="https://user-images.githubusercontent.com/50529/94812702-11fa7780-03c5-11eb-804a-bcc56f41d614.png">
<img width="621" alt="Screen Shot 2020-10-01 at 9 03 39 AM" src="https://user-images.githubusercontent.com/50529/94812703-12930e00-03c5-11eb-9eac-46278d2b2ddf.png">

**Comment by aamplugin** [comment]
@eriksays all set. The feature was implemented and will be included in the upcoming AAM 6.7.0. You can find how it all works from here https://aamplugin.com/reference/plugin#wp-cli-commands.

Any feedback is appreciated.

**Comment by eriksays** [comment]
just wanted to say thanks for this functionality. Tested and it works great!
This is going to help us deploy to 120+ sites, without having to manually configure the settings.

**Comment by joselogil** [comment]
hi @aamplugin , is this wp-cli command still available?
