### ISSUE TITLE
wp user list is empty when AAM is enabled

### ISSUE THREAD

**Issue by eriksays** [aamplugin/advanced-access-manager#155]
using wp cli -- once I activate AAM, running "wp user list" in the terminal comes back empty.
This also seems to conflict with an openid connect plugin in that the plugin tries to create existing users.
Is it possible the AAM plugin is overriding the core user functionality?

**Comment by VasylTech** [comment]
@eriksays oh, try to disable the "User Level Filter" service as I'm suspecting that would explain this side effect.

<img width="1256" alt="Screen Shot 2020-10-12 at 3 47 39 PM" src="https://user-images.githubusercontent.com/12138560/95784702-524dd580-0ca2-11eb-99ee-03b59303842c.png">

Keep me posted.

**Comment by eriksays** [comment]
that worked! thanks
