### ISSUE TITLE
Feature/Support: Define Dev and Staging Urls for AAM Complete Package

### ISSUE THREAD

**Issue by granular-s** [aamplugin/advanced-access-manager#157]
Hi,
I just purchase the AAM Complete Package. Although the license allows for unlimited dev and staging sites, your documentation says the urls must be (dev.) or (staging.). The site am currently developing is hosted at wpengine and they do not allow for dev. or staging. , I had to create staginge. and deve. How can I have these urls listed as dev and staging and not the live site?

**Comment by aamplugin** [comment]
@granular-s all set. You can now manually mark any desired domain as "dev" on this page https://aamplugin.com/license. Just enter your license key and you should be able to see all the domains that license was used on. Then you can mark any domain as dev.

Keep in mind, that the terms for the license changed with this functionality. Now, you are allowed to use the license only on 3 dev sites.
