### ISSUE TITLE
Add the ability to issue refreshable JWT token through RESTful API

### ISSUE THREAD

**Issue by aamplugin** [aamplugin/advanced-access-manager#16]
Current, the only way to issue refreshable token is to manually generate it through AAM UI. Would be nice to have the ability to issue it also through RESTful API during authentication process.

**Comment by n9yty** [comment]
In reading through many articles/approaches to using JWT in mobile apps using React Native, the idea seemed to be that you would have a short-term access token, but also a much longer-term (although not permanent) token that could be used to request a new token pair. This longer-term token can not be used to make API requests, but only used to request a new token pair (access/new refresh tokens). This allows for a short-term access token (in case it somehow is intercepted/compromised I suppose) but doesn't require the user to re-enter credentials very often as long as they use the app before the longer-term renewal token has expired and can no longer request a new set of tokens.

I have found another plugin for Wordpress that does offer this model with JWT, but the others I have found do not offer it. Will this enhancement to AAM offer that mode of operation?

**Comment by aamplugin** [comment]
@n9yty the process that you've described is the implementation based on oAuth 2.0 specification and that is something that AAM most definitely will support down the road.

For now, AAM simplifies this process by using a single JWT token. Tokens that can be refreshed have additional claim `refreshable` equals `true`.

My philosophy here is simple: "You do not bring your password to DMV if you need to renew your expiring driver's license".
