### ISSUE TITLE
INI format warning?

### ISSUE THREAD

**Issue by dannysummerlinjstartorg** [aamplugin/advanced-access-manager#160]
https://github.com/aamplugin/advanced-access-manager/blob/b0aadfce6fa0bc5f4f483a595074a06006fbad84/Application/Backend/tmpl/settings/configpress.php#L13

Just a thought/recommendation - we had messed up our permissions by not having some ConfigPress options set, but then we we set them, it still didn't work. We realized we didn't have [aam] at the top to define the INI section - we've got it now, but it would have been great if there was a warning or even automatic addition of that tag to help make things clear. I can take a look at adding a JS catch but I just wanted to through the idea out there!

**Comment by aamplugin** [comment]
@dannysummerlinjstartorg very good point. Adding the default `[aam]` to the ConfigPress if it is empty.
