### ISSUE TITLE
Access settings are not saved

### ISSUE THREAD

**Issue by Argolein** [aamplugin/advanced-access-manager#167]
WordPress version: 5.5.3
AAM Plus Package Version: 5.4.4

Problem:
Changing settings, e.g. role Autor -> Metaboxes & Widgets -> Postings -> Tags

are not saved. I check/uncheck a box, go to another role, come back and the setting are not saved.

**Comment by aamplugin** [comment]
Hello @Argolein,

Hm. Can't reproduce it. Followed your steps and settings are saved as expected. What is your AAM version?

<img width="1270" alt="Screen Shot 2021-02-15 at 10 45 09 AM" src="https://user-images.githubusercontent.com/34006503/107967342-fc07e080-6f7a-11eb-91b4-208695b8d77b.png">

**Comment by Argolein** [comment]
@aamplugin  Hi =)
AAM Version 6.7.3
Wordpress version is 5.5.3

I only have the issue within "Metaboxes & Widgets". Chages made in "Toolbar" or "Backend Menu" settings to update.

What else can I provide for debugging?

**Comment by lizannd** [comment]
@aamplugin 
I am having the same problem! WordPress version 5.6.1 and AAM version 6.7.3.  Like @Argolein my issue is only in "Metaboxes and Widgets", all other menu sections seem to be fine.  For me, I can check a box and it will stick, but if I UNcheck a box, it will not "hold", the checkmark will be there when I go back.

**Comment by aamplugin** [comment]
@lizannd gotcha.

I can confirm the issue now. The fix is coming tonight with AAM 6.7.4 release.
Thank you!
