### ISSUE TITLE
Access Policy breaks Broadcaster Plugin

### ISSUE THREAD

**Issue by SEA-NET** [aamplugin/advanced-access-manager#170]
Hello,

we are using AAM and also the Broadcast plugin for our Wordpress network. After creating the Access Policy "RESTRICT NON-MEMBER TO SITE IN MULTISITE NETWORK" we found that the Broadcaster will no longer work.

Debugging the issue showed that the blog was switched while saving the post. I think the error is in the AAM Multisite.php were the blog gets switched to the main site:
   switch_to_blog(AAM_Core_API::getMainSiteId());
and then switched back using:
   switch_to_blog($this->switch_back_blog_id);

According to Wordpress documentation the second call should use the "restore_current_blog()" command.
https://developer.wordpress.org/reference/functions/restore_current_blog/

Best regards,
SEA-NET

**Comment by SEA-NET** [comment]
Hi,
 I patched the workaround from the Wordpress docs into Multisite.php.
Now the broadcaster is working with the access policy enabled.

Please ship a patch.

Thanks and best regards,
SEA-NET

**Comment by aamplugin** [comment]
Thank you @SEA-NET,

Most definitely I'm going to evaluate this issue and include the fix in the next minor release.

Thank you!
