### ISSUE TITLE
Bug - WP Notice in logs for fread error with /aam-complete-package/

### ISSUE THREAD

**Issue by terrance-orletsky-d7** [aamplugin/advanced-access-manager#177]
Hi - Awesome plugin, thanks for all your work!

It appears that WordPress is attempting to load AAM during 'admin-ajax' calls using a plugin folder name (`/plugins/aam-complete-package/`), and thus is filling up my logs with notices:

<img width="1440" alt="Fullscreen_2021-05-16__7_10_PM" src="https://user-images.githubusercontent.com/78424466/118424356-f2763d80-b67b-11eb-9b34-9130642436d9.png">

Is there a resolution for this planned?

**Comment by aamplugin** [comment]
@terrance-orletsky-d7 thank you. I think I found the root cause. The fix is coming shortly.
