### ISSUE TITLE
Super-Admin is unable to re-assign roles in network sites

### ISSUE THREAD

**Issue by terrance-orletsky-d7** [aamplugin/advanced-access-manager#180]
**CRITICAL - Impedes Core Functionality**

---

GIVEN
AAM is installed,
Premium/ complete package
and the WP site is a multisite subdomain installation
and multiple roles is enabled

WHEN
A Super-Admin user tries to edit(add or remove) one, 
or multiple, roles for a user, in a network (subdomain) site,
in the user profile screen at `/wp-admin/user-edit.php?user_id=[id]`

THEN
The error message is displayed:
```
Sorry, you are not allowed to give users that role.
```

---

EXPECTED BEHAVIOUR:

As a Super-Admin, I should be able to assign any/all roles to any user, in any site

---

ADDED INFO...

A Super-Admin is able Add a New User to the site and assign roles *at that time*...
however editing the roles for the same user immediately afterwards surfaces the error reported above.

Deactivating AAM removes the multi-select for roles in the edit screen,
and then there is no error when changing roles for the same user

**Comment by terrance-orletsky-d7** [comment]
@VasylTech @aamplugin  I've confirmed that this is a regression which was introduced with 6.7.6

Rolling back to the previous release 6.7.5 fixes this problem...

**Comment by terrance-orletsky-d7** [comment]
@VasylTech @aamplugin  

Rolling back to 6.7.5, then applying this patch, is what is a workaround that allows our multi-site to function, for now:

Thanks for your previous work on this - I hope there can be a quick resolution to this blocker to core functionality in yoru next release.

**My workaround:**

File to modify:
```
/wp-content/plugins/advanced-access-manager/application/Backend/tmpl/user/multiple-roles.php
```

Modified File contents:
```
<?php /** @version 6.0.1 */ ?>
<?php /** workaround / patched by terrance.orletsky@domain.7.com - may 28, 2021 */ ?>
<?php if ( defined( 'AAM_KEY' ) ) { ?>
    <?php if ((! defined('IS_PROFILE_PAGE') || ! IS_PROFILE_PAGE) && ! is_network_admin() && (empty($user) || current_user_can('promote_user', $user->ID))) { ?>
        <?php $user = ( $param === 'add-new-user' ? null : $param ); ?>
        <?php global $pagenow;
        // if ('user-edit.php' === $pagenow || 'user-new.php' === $pagenow) { 
       // this doesnt work on add user-new screen - just load multi-select on user-edit
        if ('user-edit.php' === $pagenow) { ?>
        <table class="form-table">
            <tr>
                <th><?php echo esc_html('User Roles', AAM_KEY); ?></th>
                <td>
                    <div class="wp-tab-panel">
                        <ul>
                            <?php $roles = (! empty($user->roles) ? $user->roles : array( 'staff' ));  // user->roles check AND this needs to be the site's default role?>
                            <?php foreach (get_editable_roles() as $id => $role) { ?>
                                <li>
                                    <label>
                                        <input type="checkbox" name="aam_user_roles[]" value="<?php echo esc_attr($id); ?>" <?php checked(in_array($id, $roles)); ?> />
                                        <?php echo esc_html(translate_user_role($role['name'])); ?>
                                    </label>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                </td>
            </tr>
        </table>
        <!-- Remove standard WordPress roles selector  -->
        <!--This doesn't work on either  - commenting it out -->
        <!-- <script>
            (function($) {
                $(document).ready(function() {
                    if ($('.user-role-wrap').length) {
                        $('.user-role-wrap').remove();
                    } else if ($('#role').length) {
                        $('#role').parent().parent().remove();
                    }
                });
            })(jQuery);
        </script> -->
        <?php
        }
    }
}
```

**Comment by terrance-orletsky-d7** [comment]
The modified code above results in this: (see attached screenshots)

![aam-patch](https://user-images.githubusercontent.com/78424466/120059456-ee98d280-c00e-11eb-9d48-79492e96d074.png)


Incidentally, taking a second step to edit the user and assign multiple roles is a totally acceptable resolution, to me.

If you want me to submit a PR, please lmk.

T

**Comment by terrance-orletsky-d7** [comment]
@VasylTech @aamplugin  Just checking in - this is blocking us from launch.   

Are you planning to resolve this new bug that was introduced on the latest version?

Thanks!

**Comment by aamplugin** [comment]
@terrance-orletsky-d7 just tried to reproduce the issues that you've outlined earlier without any luck. I'm able to add users to the sites with multi-role support without any issues. I'm using clean Multisite WordPress setup with AAM and Complete Package enabled. Please confirm that you can reproduce the issue on a different WordPress site.

**Comment by terrance-orletsky-d7** [comment]
Hi there,

I've tested locally, and the issue I reported from 6.7.5 (which I had to
patch) appear to now be resolved, and the regression I reported when
installing version 6.7.6 (which I had to roll back from) also appears to
have now been resolved, upon installing version 6.7.7

Thank you for the update, I will now update our development environment
with the latest version

Cheers!
Terrance

**Comment by JulienBarreira** [comment]
Hi @terrance-orletsky-d7,

Can you confirm the problem is fixed for you with the version 6.7.7 in your development environment?

I got the same issue since the 6.7.6 version as mentioned here: https://wordpress.org/support/topic/cant-update-user-role-as-super-admin-after-upgrading-to-latest-version/

Rolling back to the 6.7.5 version is fixing the issue for me (even without the file edit), but the 6.7.7 still has the issue (locally, in development environment & in production).

I also tried to rollback to the 6.7.5, updating the file with your content and then upgrading to the 6.7.7 but the regression is still there.

**Comment by terrance-orletsky-d7** [comment]
@JulienBarreira  

I think that perhaps that issue is unrelated to the update, but is specific to an issue with importing the data, using the AAM settings import/export feature

Upon a fresh installation, the issue does not occur, with version 6.7.7

HOWEVER

After... I tried to export my settings, using AAM, then import (even using the same file, same site), then the bug appears!  Can you recreate?

T

**Comment by terrance-orletsky-d7** [comment]
Confirmed - I sadly was just able to recreate this...

Steps to recreate:
- Export AAM settings
- Import AAM settings
- Attempt to assign multiple user roles to a user
- -Error - see attached

<img width="999" alt="WordPress_›_Error" src="https://user-images.githubusercontent.com/78424466/126640423-a9c0963d-a4e6-48b9-9999-dd98971346f3.png">

AND this is a major blocker, as we cannot migrate settings from a dev site to production!!!

**Comment by aamplugin** [comment]
Hello folks. Better later than never. I think I was able to pinpoint the root cause and AAM 6.9.4 will contain a fix (releasing tonight). Please give a try.
