### ISSUE TITLE
Policy doesn't do the same as Manual Settings

### ISSUE THREAD

**Issue by DamonVogel** [aamplugin/advanced-access-manager#182]
Using the Wicked Folders Pro plugin, I go to Posts & Terms and set the taxonomy wf_page_folders to Hidden for all areas (Frontend, Backend, RESTful API ). **This functions well.** 
I create an Access Policy from a user that has ONLY that setting configured. I create a second user clean, and apply that Access Policy to this user. **This does not work.**

**Comment by aamplugin** [comment]
@DamonVogel can you please include your access policy? This is quite basic setup and I'm wondering if the policy is not defined correctly.
