### ISSUE TITLE
New update removed access

### ISSUE THREAD

**Issue by jcamacho0505** [aamplugin/advanced-access-manager#183]
Hello

I updated my plugin for my website and it removed the access to forms that i have for roles created, only my admin role works.  Is this something you can help me with?

**Comment by jcamacho0505** [comment]
I deactivated this plugin and my user access started working again....any thoughts?

**Comment by aamplugin** [comment]
@jcamacho0505 it is hard to say based on your description. There are many possibilities why that could be the case and it all depends on your website setup. Can you explain what "forms" do you refer to? Can you reproduce this on other website?
