### ISSUE TITLE
Error parsing config string: syntax error, unexpected '(' in Unknown on line 2

### ISSUE THREAD

**Issue by oivinds** [aamplugin/advanced-access-manager#209]
Disabled all plugins, except aam. Wordpress core 6.0.1.

Error parsing config string: syntax error, unexpected '(' in Unknown on line 2

EDIT: Went to settings - Reset AAM settings. The error disapeared. 
I think the only aam configuration I have made was setting a capability setting.

**Comment by aamplugin** [comment]
Hello @oivinds,

I'm guessing you have the error displayed like this one, am I right?

<img width="1267" alt="Screen Shot 2022-07-30 at 1 08 18 PM" src="https://user-images.githubusercontent.com/34006503/181934277-392ad85f-1a0b-4943-859e-db4fe8d01362.png">

If that is the case, this indicates that you did not provide the valid INI-format configuration on the Settings->ConfigPress tab:

<img width="1271" alt="Screen Shot 2022-07-30 at 1 09 45 PM" src="https://user-images.githubusercontent.com/34006503/181934323-1ee33ca1-985d-4651-b103-0e39938142dd.png">

This does not break AAM or how it functioning, however, you would want to fix the config or completely clear it. If you do not know what is possibly wrong with the config, just post it here and I'll help you.
