### ISSUE TITLE
Catalog name 'Application' is capitalized, but name in import in autoloader.php is not - breaking the plugin on linux

### ISSUE THREAD

**Issue by Czpl** [aamplugin/advanced-access-manager#210]
https://github.com/aamplugin/advanced-access-manager/blob/51a778f75cac90f5eb6c50d7132516a7502b1266/autoloader.php#L66

**Comment by Czpl** [comment]
Causes `PHP Fatal error:  Uncaught Error: Class "AAM_Core_Config" not found in /var/www/html/wp-content/plugins/advanced-access-manager/aam.php`, running on docker on linux. 
Renaming the directory to 'application' fixed the issue. 
MacOS is not case sensitive, so the problem was tricky to find.

**Comment by aamplugin** [comment]
Hello @Czpl,

Hm, that is odd. Indeed, it was an issue back in I guess 2018-ish, but the directory names were fixed. In AAM 6+ the `application` directory is all in lowercase if you install AAM from the official WordPress repository https://plugins.svn.wordpress.org/advanced-access-manager/tags/6.8.3/

**Comment by aamplugin** [comment]
@Czpl also update Github repository accordingly. Thank you for the feedback
