### ISSUE TITLE
URI filtering doesn't respect roles when using JWT

### ISSUE THREAD

**Issue by K6TU** [aamplugin/advanced-access-manager#233]
Prior to AAM 6.9.1 this was functional...

1. Site is configured to block URI access for all visitors to /wp-json/* and allow /wp-json/aam/*
2. A specific user with Editor roles is used by client access to the REST interface, the JWT took is obtained ok
3. The URI filtering for the specific user Role of the Editor is set to allow access to /wp-json/*

Prior to 6.9.1 this configuration worked.  With 6.9.1 and forward, the JWT is still obtain successfully in step 2 but subsequent requests are redirected to the login page.

Allowing Vistor access to /wp-json/* is required for subsequent requests using the token to be completed.

This can easily be reproduced using Postman.

Reverting to 6.9.0 still functions with the original (and desired) behavior.

Is the current behavior in 6.9.1 and greater...
a) The original intent having fixed a defect in prior releases that should have enforced the new behavior
b) A chance in 6.9.1 that broke URI filtering by roles

**Comment by aamplugin** [comment]
@K6TU,

Thank you for the feedback. This issue was pinpointed and resolved. New release is coming tonight 6.9.4. Let us know if that is still a problem.
