### ISSUE TITLE
map_meta_cap was called incorrectly

### ISSUE THREAD

**Issue by cbdgftqs** [aamplugin/advanced-access-manager#269]
hello :
I have several notice in my debug.log file :
Function map_meta_cap was called incorrectly. When checking for the edit_post capability, you must always check it against a specific post. Please see Debugging in WordPress for more information. (This message was added in version 6.1.0.)  in /usr/local/lsws/wp/html/wp-includes/functions.php on line 5865
I have disabled other plugins and use the theme [Twenty Twenty-Three]
WordPress 6.2 and aam 6.9.9

**Comment by aamplugin** [comment]
@cbdgftqs thank you for the message. Unfortunately there is not enough information in your message to relate this WordPress debug notice to AAM.

Can you please provide the full PHP error trace and explain how this issue can be reproduced?
