### ISSUE TITLE
Can't see AAM settings when editing page

### ISSUE THREAD

**Issue by hpooni** [aamplugin/advanced-access-manager#270]
Just updated plugin to v6.9.9 and can no longer see AAM settings usually displayed below the page settings. Works fine when downgraded to v6.9.8. Using PHP 7.4.

**Comment by hpooni** [comment]
Yep, that did the trick. Thank you.

**Comment by tonydjukic** [comment]
I've got a client site running 6.9.10 and have toggled the setting on and off again repeatedly, they still can't see 'in-post' AAM  Access Manager meta box/panel.  I don't think the issue is fully addressed.
