### ISSUE TITLE
Feature Request: Ability to create API tokens limited to GET requests

### ISSUE THREAD

**Issue by Kanesho1924** [aamplugin/advanced-access-manager#280]
I'm currently using the Advanced Access Manager (AAM) plugin for WordPress and while it's a valuable tool, I've encountered a limitation. The plugin doesn't seem to allow JWT API tokens to be limited to GET requests only, despite attempts to manually disable POST, DELETE, and PUT. Is there a way to achieve this with the current plugin features? If not, would it be possible to consider adding this feature in a future update?

**Comment by aamplugin** [comment]
Hello @Kanesho1924,

Very good question. Yes it is possible and we literally last week actually reviewed all the ConfigPress options that fine-tune how JWT service works.

We are planning to release AAM 6.9.11 tonight and the option [service.jwt.bearer](https://aamportal.com/plugin/advanced-access-manager/configpress/service-jwt-bearer) is what you are looking for. In your case you need to narrow down the places that AAM looks for the token to just `query_param` as following:

```ini
[aam]
service.jwt.bearer = "query_param"
```
