### ISSUE TITLE
Compatibility with PHP 5.6

### ISSUE THREAD

**Issue by aamplugin** [aamplugin/advanced-access-manager#287]
With older PHP versions there are several places in the code that cause this fatal errors.

**Comment by patrick-7-7-7** [comment]
I see all the action happens here on Github, so I refer you to this: https://wordpress.org/support/topic/php-5-6-compatibility-and-oter/
The highlight is this fatal error causing code:
"advanced-access-manager/application/Core/Jwt/Manager.php line 366
protected function jsonEncode(array $input): *string*"
