### ISSUE TITLE
Can’t manage Backend Menu

### ISSUE THREAD

**Issue by paulojmdias** [aamplugin/advanced-access-manager#356]
Hi,

I’m using AAM in the latest version 6.9.25 and can’t manage the backend menu items. I already tried to disable the plugins, uninstall AAM, and install it again, also deleted all the entries of AAM in the wp_options table but I still have no luck.

Error:

```
Try to refresh the page. If that doesn't resolve the issue, it's possible that the current user may lack the necessary privileges to access any backend menu items. Another frequently encountered problem is the deactivation of transients (a native caching method in WordPress). Often, third-party caching plugins offer the option to disable transients, so if you're using one, look for the settings that allow you to re-enable them.
```

The printscreen of the error is below.

![image](https://github.com/aamplugin/advanced-access-manager/assets/44772900/0fec567e-08fb-4e63-9b25-13970799565f)

**Comment by aamplugin** [comment]
Hello @paulojmdias,

This is very odd, but let me explain how AAM prepares the admin menu list and you might be able to find out where is the problem.

When you load AAM page, AAM prepares a cache properties that is stored in `wp_options` table. The name of the property is `aam_cache`. When page is loaded, AAM sends an ajax API call to fetch the admin menu data.

So, it is most likely two scenarios that I can think of:
- You are at 100% space capacity on your server, so no new db records can be inserted. AAM cache record requires only a couple of KB of space but we've seen several instances of such case.
- You have an aggressive caching enabled that just serves already cached values. We've seen few times websites setup with caching plugins that despite properly saved data, still served staled data from their cache storage. If you have any caching plugins, try to purge cache.

**Comment by aamplugin** [comment]
Recently we also noticed that PHP serialization breaks when menu items contains symbols like emojis. This was fixed in the latest AAM release. So you should be able to manage Backend Menu with the latest update.
