### ISSUE TITLE
The list of terms for any selected taxonomy is not listed

### ISSUE THREAD

**Issue by aamplugin** [aamplugin/advanced-access-manager#376]
On the "Posts & Terms" tab, when selecting any Taxonomy, the list does not load.

**Comment by gtconceptstim** [comment]
The latest version 6.9.30, did not resolve the issue for me. The Woocommerce product catergories are still not working sadly, the products load. But when I select the product categories from the dropdown the list remains empty. There should be 12 categories.

**Comment by aamplugin** [comment]
@gtconceptstim appreciate your follow-up and sorry for all these issues. We are in the process to move AAM to 7.0.0. It is a major release, so, some things may be a bit bumpy.

The issue was found and resolved. You can replace the following file on your server and that'll do the trick https://github.com/aamplugin/advanced-access-manager/blob/master/media/js/aam.js
