### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined function switch_to_user_locale

### ISSUE THREAD

**Issue by DanWin** [aamplugin/advanced-access-manager#398]
The function switch_to_user_locale was introduced in WordPress 6.2.0 and doesn't exist in older WP versions. The required WordPress Version for this plugin is stated as 5.2.0 or higher. So either we will need to increase the minimum version requirements, or an alternative implementation compatible with older versions of WordPress should be implemented.

[10-Jul-2024 09:26:49 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function switch_to_user_locale() in /var/www/html/wp-content/plugins/advanced-access-manager/application/Restful/MuService.php:34

**Comment by aamplugin** [comment]
@DanWin thank you for the report. We'll fix it asap.
