### ISSUE TITLE
Custom user roles not copying correctly

### ISSUE THREAD

**Issue by esd112-web** [aamplugin/advanced-access-manager#419]
I have attempted to submit multiple support emails since discovering this issue months ago for the premium version but have not heard back at all.

Issue:

I’m running AAM and the Premium Add-On and the capability settings and menus settings aren’t copying over properly when I’m copying a custom role to create a new custom role. I just updated on my staging to the latest version of both plugins and this is still happening. I tried enabling the setting for “multiple roles support” per the chatbox suggestion and that didn’t work either. Please advise how it can be fixed as I've been using this plugin for years and need to be able to successfully clone user roles to create new user types.

<img width="1351" alt="Screenshot 2024-08-06 at 11 19 46 AM" src="https://github.com/user-attachments/assets/df99be37-6712-4a1f-b21f-20956e55d55f">
<img width="1343" alt="Screenshot 2024-08-06 at 11 19 53 AM" src="https://github.com/user-attachments/assets/d21d0598-e38a-461a-aef4-11ab64366cbd">
<img width="1489" alt="Screenshot 2024-06-27 at 10 08 59 AM" src="https://github.com/user-attachments/assets/77eed84e-8311-4eff-b242-c963f0e053c8">
<img width="605" alt="Screenshot 2024-06-27 at 10 09 12 AM" src="https://github.com/user-attachments/assets/ec0372bf-854d-4863-94ff-74e994db43a7">
<img width="1478" alt="Screenshot 2024-06-27 at 10 09 29 AM" src="https://github.com/user-attachments/assets/92f60927-8a58-4274-b127-b5a333c2ee41">

**Comment by aamplugin** [comment]
@esd112-web thank you for the report. Looking into it. Will come back with updates shortly.
