### ISSUE TITLE
DataTables warning and REST API Forbidden

### ISSUE THREAD

**Issue by Ezyweb-uk** [aamplugin/advanced-access-manager#420]
AAM v6.9.38 installed.
On a live site in Settings > Core Settings, I changed the status of the 'RESTful WordPress API' which I believe blocked the rest API such that I could no longer enable it. I received the DataTables warning and ajax warnings.

Then on a duplicate test site, I checked that /wp-json was returning data, then I changed the 'RESTful WordPress API' to disabled and found it would not change back to enabled, and the same warnings appeared.

I compared the option values for 'aam_config' between the live site and a backup of the test site, the values are below:
live site:  a:1:{s:21:"core.settings.restful";b:0;}
test site backup:  'aam_config' did not exist.

In the live site database I deleted the option 'aam_config' which then unblocked the rest api. (I also deleted another option 'aam_configpress' which had the value a:0:{} ).

I won't be touching this setting again!

**Comment by aamplugin** [comment]
@Ezyweb-uk thank you for the message. That is correct, by disabling RESTful API, you basically cutting off the entire AAM UI functionality as we quite literally moved 99% of all API calls to RESTful.

We will consider to improve user experience with AAM UI when RESTful API is disabled to prevent DataTable errors and further confusion; and at least allow to re-enable the RESTful API if it was disabled by mistake.

If you are trying to protect your RESTful API, I would suggest to check this article https://aamportal.com/article/security-wordpress-restful-api-endpoints.
