### ISSUE TITLE
Redirect in multilingual site (Polylang) is problematic

### ISSUE THREAD

**Issue by markdimi** [aamplugin/advanced-access-manager#58]
AAM:6.3.3
Wordpress: 5.3.2

Selecting an existing page for redirection is problematic in a few ways. I am using polylang and I have two languages in my site (Greek and English). I want to create a redirection rule for a page in both languages so naturally I should apply this rule for both versions (GR and EN) of the page. 

However when I select the existing page choice for redirection, it shows only the pages in one language (GR or EN) for both versions. So I can choose a Greek page (or English, it's a random happenstance) for a redirection for both versions of a page when naturally I would need to select a Greek page when redirecting from a Greek page and an English page when redirecting from a English page. Or at least, return all the pages and let me select the one I want.

But this isn't the case. So what I do is set the redirection for one language via the existing page choice and the other by giving the full url of the destination.

**Comment by aamplugin** [comment]
Great feedback and honestly you are not the first one that experiences this type of problem.

I'm still learning, occasionally, about Polylang implementation. And so far I've noted that it does quite a bit of funky stuff under the hood when it translates posts/pages/categories to multiple languages. It actually duplicates a record as many times as many languages you enable.

I would have to work with their plugin developer to figure out the correct integration point and most definitely we will prioritize this implementation. Can't give you any dates at the moment.

**Comment by aamplugin** [comment]
I've contacted Polylang plugin owner and the response was discouraging. It appears that the plugin's owner has no much interest to work on possible integration, so I had to deprioritize this implementation for now.
