### ISSUE TITLE
Shortcodes - Content filter not yet compatible with multiple roles

### ISSUE THREAD

**Issue by eulores** [aamplugin/advanced-access-manager#6]
Only the first role assigned to a user is checked.
The line of code responsible for this is in the file Application\Shortcode\Strategy\Content.php:60

I have replaced the line
`$user = array((string)AAM::getUser()->ID, AAM::getUser()->roles[0]);`
by
`$user = array((string)AAM::getUser()->ID);`
`array_push($user, ...AAM::getUser()->roles);`

That fixes it for me!
But I have little to no experience coding in PHP, so don't know if this is the right way.

**Comment by VasylTech** [comment]
Great finding @eulores. There are a couple things I'm going to modify in your suggested code and the fix is going to be released in next minor update. Thank you
