### ISSUE TITLE
The toolbar is not displayed on some roles and user in frontend

### ISSUE THREAD

**Issue by Sinapars** [aamplugin/advanced-access-manager#60]
Hi Team ,
After some changes have been made to some roles and users, the toolbar will not be displayed at the site frontend 
The settings are checked Show Toolbar when viewing site
The interesting thing is that this problem only exists on some of the users in which they are role, not all
i'm use jannah template
wordpress version is 5.3.2
aam plugin is latest version
sorry for week english 
best regards

**Comment by Sinapars** [comment]
this problem is resolved when disbale booked plugin 
https://getbooked.io/

**Comment by aamplugin** [comment]
Thank you for the feedback. It is most likely the Booked plugin has an option that allows re-enabling toolbar. You may try to find some answers in their documentation or send a support message to the team. For now, I'm closing this thread
