### ISSUE TITLE
Wordpress Plugin Conflict: Advanced Custom Fields Pro

### ISSUE THREAD

**Issue by adambichler** [aamplugin/advanced-access-manager#9]
**Conflict After Update to Version 6.0.1**
Seems like there is a conflict with the ACF Plugin Pro (5.8.7). When AAM is updated to Version 6.0.1 and activated with Wordpress (5.3) it is not possible to edit consisting ACF Field Groups. 
Before updating the plugin this was possible with AAM 5.9.x

The backend only loads WP sidebar and top menu bar. Console throws no errors tough.

**Comment by adambichler** [comment]
Another conflict with the ACF Plugin when updating to version 6.0.5:
The ACF-User-Field is not able to load the values of the user (id and so on) when viewing the site as a logged out user! It works when a user is logged in.  
In the previous version of AAM this was no problem.

**Comment by rodadas-ali** [comment]
> Another conflict with the ACF Plugin when updating to version 6.0.5:
> The ACF-User-Field is not able to load the values of the user (id and so on) when viewing the site as a logged out user! It works when a user is logged in.
> In the previous version of AAM this was no problem.

This is still not working on version 6.6.2 with Advanced Custom Fields 5.9.1

**Comment by abombelli** [comment]
Is this fixed or any workaround.
I'm experiencing the same issue.
