### ISSUE TITLE
Login form not rendered in aam 6+

### ISSUE THREAD

**Issue by sebastiande** [aamplugin/advanced-access-manager#90]
HI,

I added a short code with version 5.x.x to my page:

`[aam context="login" callback="getLoginCode" id="login"]`

After upgrading to version 6+ the form isn't rendered anymore. I can't find any information that this isn't supported anymore and even the documentation tells something about the login form.

Is this a bug?

Thanks!

**Comment by aamplugin** [comment]
That is correct. The login shortcode was removed in AAM 6 as stated in the article ["Advanced Access Manager next generation"](https://aamplugin.com/article/advanced-access-manager-next-generation).

We might return it back, however, so far only a couple of people expressed interest in this shortcode.

**Comment by aamplugin** [comment]
This feature is scheduled to be added in the next AAM 6.6.0 release.

**Comment by aamplugin** [comment]
The new shortcode is added `[aam-login]` that accepts two arguments:

- `class`: CSS class that will be added to the login form;
- `redirect`: URL to redirect to after successful login;
